name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - '.github/workflows/docker-build.yml'
    tags: [ 'v*' ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: amizzo/dockfuse
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') || github.ref == format('refs/heads/{0}', 'master') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha,format=short
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Update Docker Hub Description
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: amizzo/dockfuse
          readme-filepath: ./DOCKER_HUB_README.md
          short-description: "Docker container for mounting S3 buckets as local volumes using s3fs-fuse"
      
      - name: Notify on Success
        if: success()
        run: |
          echo "✅ Docker image successfully built and pushed to Docker Hub"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
      
      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Failed to build or push Docker image" 